apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: httpbin-healthcheck
  name: httpbin-healthcheck
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/httpbin-healthcheck
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: httpbin-healthcheck
    spec:
      containers:
      - image: kennethreitz/httpbin
        imagePullPolicy: Always
        name: httpbin-healthcheck
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File