AWSTemplateFormatVersion: "2010-09-09"
Parameters:  
  ClusterStackName:
    Type: String
    Default: MyClusterStack

Resources:
  Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: k8s-spot-interrupt-handler
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              AWS: 
                Fn::ImportValue: 
                  !Sub "${ClusterStackName}-NodeGroupInstanceRoleARN"
      Policies:
        - PolicyName: spot-interrupt-handler-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Action:
                  - elasticloadbalancing:DeregisterTargets
                  - elasticloadbalancing:DescribeTags
                  - elasticloadbalancing:DescribeTargetGroupAttributes
                  - elasticloadbalancing:DescribeTargetGroups
                  - tag:GetResources
                Effect: Allow
                Resource: '*'